# Generated by Django 5.2 on 2025-04-10 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('tr', 'Turkish'), ('fr', 'French'), ('es', 'Spanish'), ('de', 'German'), ('zh', 'Chinese'), ('jp', 'Japanese')], default='en', max_length=2)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.artist')),
            ],
        ),
    ]
