# Generated by Django 5.2 on 2025-04-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='song_title',
            new_name='album_title',
        ),
    ]
