# Generated by Django 5.2 on 2025-04-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_song_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
